version: "3.7"
services:
  mongo:
    image: mongo
    volumes:
      - db:/data/db
  app:
    build: .
    restart: ${DOCKER_RESTART_MODE:-unless-stopped}
    links:
      - 'mongo:mongo'
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}
    command: 'nodemon dist/index.js'

volumes:
  db:


